import { fileURLToPath, URL } from 'node:url';
import { type Plugin, defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

/**
 * Emit the LLM-facing contract alongside the app.
 *
 * `/llms.txt` tells any language model how to write a plan this app can read,
 * and `/catalog.json` gives it the built-in movement and equipment ids. Both
 * are generated from `src/spec/planSpec.ts`, which reads the same catalogue
 * modules the parser does — so the documentation cannot promise a field the
 * parser rejects.
 *
 * Generated at build rather than committed for the same reason. A checked-in
 * copy is a copy that goes stale the first time someone adds an exercise.
 */
function planSpecPlugin(): Plugin {
  return {
    name: 'rackfile-plan-spec',
    apply: 'build',
    async generateBundle() {
      // Imported inside the hook so the catalogue is resolved through Vite's
      // pipeline, with the `@/` alias and TypeScript already handled.
      const { buildCatalog, buildLlmsTxt } = await import('./src/spec/planSpec.js');

      this.emitFile({ type: 'asset', fileName: 'llms.txt', source: buildLlmsTxt() });
      this.emitFile({
        type: 'asset',
        fileName: 'catalog.json',
        source: JSON.stringify(buildCatalog(), null, 2),
      });
    },
  };
}

/**
 * The service worker is generated by Workbox from the real build manifest, so
 * every deploy revisions its own precache. That replaces the old routine of
 * hand-bumping a CACHE constant in sw.js and hoping nobody forgot.
 */
export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: true,
    // Fonts are small and self-hosted; inlining them would bloat the JS bundle.
    assetsInlineLimit: 4096,
  },
  server: {
    port: 5173,
    open: false,
  },
  preview: {
    port: 4173,
  },
  plugins: [
    planSpecPlugin(),
    VitePWA({
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['icon.svg', 'icon-192.png', 'icon-512.png'],
      manifest: {
        name: 'Rack & File',
        short_name: 'Rack&File',
        description: 'Personal training log for a 7-day plan.',
        start_url: './',
        scope: './',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#14171A',
        theme_color: '#14171A',
        categories: ['health', 'fitness', 'lifestyle'],
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        // Exercise media will grow well past the 2 MiB default once photos land.
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
        cleanupOutdatedCaches: true,
        navigateFallback: 'index.html',
        runtimeCaching: [
          {
            // Roadmap: exercise photos and video posters served from /media.
            urlPattern: /\/media\/.*\.(?:png|jpg|jpeg|webp|avif|gif|mp4|webm)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'rackfile-media',
              expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 60 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
});
