import { fileURLToPath, URL } from 'node:url';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

/**
 * The service worker is generated by Workbox from the real build manifest, so
 * every deploy revisions its own precache. That replaces the old routine of
 * hand-bumping a CACHE constant in sw.js and hoping nobody forgot.
 */
export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: true,
    // Fonts are small and self-hosted; inlining them would bloat the JS bundle.
    assetsInlineLimit: 4096,
  },
  server: {
    port: 5173,
    open: false,
  },
  preview: {
    port: 4173,
  },
  plugins: [
    VitePWA({
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['icon.svg', 'icon-192.png', 'icon-512.png'],
      manifest: {
        name: 'Rack & File',
        short_name: 'Rack&File',
        description: 'Personal training log for a 7-day plan.',
        start_url: './',
        scope: './',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#14171A',
        theme_color: '#14171A',
        categories: ['health', 'fitness', 'lifestyle'],
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        // Exercise media will grow well past the 2 MiB default once photos land.
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
        cleanupOutdatedCaches: true,
        navigateFallback: 'index.html',
        runtimeCaching: [
          {
            // Roadmap: exercise photos and video posters served from /media.
            urlPattern: /\/media\/.*\.(?:png|jpg|jpeg|webp|avif|gif|mp4|webm)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'rackfile-media',
              expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 60 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
});
